image: registry.gitlab.memleak.pl:443/flat/build-images/android

before_script:
  - export PATH=$PATH:/usr/local/android-sdk-linux/platform-tools/

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    expire_in: "2 weeks"
    paths:
    - app/build/outputs/

build-release:
  stage: build
  script:
    - ./gradlew assemble
  artifacts:
    paths:
    - app/build/outputs/
  only:
    - /^v.*$/

unitTests:
  stage: test
  script:
    - ./gradlew test
